services:
  db:
    restart: always

  django:
    restart: always
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    image: nginx:alpine
    container_name: lifting_log_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../lifting-log-infra/nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - /var/log/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - django
      - grafana

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../../lifting-log-infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  static_volume:
  prometheus_data:
  grafana_data:
