services:
  db:
    image: mysql:8.0
    container_name: lifting_log_db
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"
      interval: 5s
      timeout: 5s
      retries: 55
      start_period: 5s
    restart: always

  django:
    container_name: lifting_log_django
    image: hamzahuda/lifting-log-backend:latest
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_volume:/app/staticfiles
    restart: always

  nginx:
    image: nginx:alpine
    container_name: lifting_log_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - /var/log/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - django
      - grafana

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mysql_data:
  static_volume:
  prometheus_data:
  grafana_data:
