name: Production Deployment Pipeline

on:
    push:
        branches:
            - main
    repository_dispatch:
        types: [app_code_updated]

jobs:
    deploy-to-prod:
        runs-on: ubuntu-latest

        steps:
            - name: Execute Deployment Commands Over SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd ~/lifting-log-infra
                      git checkout main
                      git pull origin main

                      docker compose -f docker-compose.prod.yml pull

                      docker compose -f docker-compose.prod.yml up -d --always-recreate-deps

                      docker compose -f docker-compose.prod.yml exec -T django python manage.py migrate --noinput

                      docker image prune -f
